site_name: scraby
site_description: Project documentation with Markdown.
repo_url: https://github.com/dsp-shp/scraby
repo_name: dsp-shp/scraby
# Extra properties
theme:
  name: material
  locale: en
extra_css:
    - css/extra.css
# Navigation
nav:
  - "Overview": index.md
  - Get started:
    - quick_start.md
