name: Code analysis

on: [push]

env:
  DEFAULT_PYTHON: '3.11'

jobs:
  linters:
    name: Linters
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Upgrade pip
        run: python -m pip install --upgrade pip setuptools wheel
      - name: Install dependencies
        run: |
          python setup.py egg_info; \
          sed -e '/^\[/s/^.*//;' -e '/^$/d;' *.egg-info/requires.txt > requirements.txt; \
          pip install -r requirements.txt
          echo "CODEQL_PYTHON=$(which python)" >> $GITHUB_ENV
      - name: Run pylint
        run: pylint $(git ls-files '*.py')
      - name: Run mypy
        run: mypy $(git ls-files 'scraby/**/*.py')
  codeql:
    name: CodeQL
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python ${{ env.DEFAULT_PYTHON }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.DEFAULT_PYTHON }}
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: python
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: /language:python
